version: '3.7'

services:
  aws-spring:
    build:
      context: .
      dockerfile: Dockerfile
    image: aws-spring
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
    ports:
      - 9010:8080 # Application port
